// GENERATED by tools/gen_constants.py from shared/constants.json.
// Do not edit. Edit the JSON and regenerate.

#ifndef INJECTION_CONSTANTS_H
#define INJECTION_CONSTANTS_H

// ---- shared with the host ----
#define N 500  // Samples per scan. The trace block is exactly 2*N raw bytes.
#define NUM_PEAKS 20  // Max peaks reported per channel in a peaks block.
#define MAX_CLUSTERS 3  // Max tracked clusters per channel. Bounds tracking block length.
#define ADC_BITS 12  // ADC resolution. The host validates trace payloads with it.
#define DAC_MAX 4095  // Full-scale DAC code.
#define COMMAND_BUFFER 64  // Firmware command buffer; longer lines are discarded with a [WARN].

// ---- firmware only ----
#define MAX_SCANS 100  // Scans averaged during initialisation.
#define HIGH_THRESH 800  // Slower/high peak discrimination threshold, ADC counts.
#define LOW_THRESH 400  // Xbeam/low peak discrimination threshold, ADC counts.
#define NOISE_THRESH 100  // Minimum prominence for a peak, ADC counts.
#define CLUSTER_GAP 75  // Max sample separation within one cluster.

#endif  // INJECTION_CONSTANTS_H
