"""GENERATED by tools/gen_constants.py from shared/constants.json.

Do not edit. Edit the JSON and regenerate.
"""

from __future__ import annotations

#: Samples per scan. The trace block is exactly 2*N raw bytes.
N = 500
#: Max peaks reported per channel in a peaks block.
NUM_PEAKS = 20
#: Max tracked clusters per channel. Bounds tracking block length.
MAX_CLUSTERS = 3
#: ADC resolution. The host validates trace payloads with it.
ADC_BITS = 12
#: Full-scale DAC code.
DAC_MAX = 4095
#: Firmware command buffer; longer lines are discarded with a [WARN].
COMMAND_BUFFER = 64

#: Highest valid high byte of a little-endian ADC sample. A valid
#: trace has every high byte at or below this; ASCII never is, which
#: is how a short trace padded by the next block's text is detected.
MAX_SAMPLE_HIGH_BYTE = (1 << (ADC_BITS - 8)) - 1

#: Names that must agree with the firmware, for the startup check.
SHARED = ("N", "NUM_PEAKS", "MAX_CLUSTERS", "ADC_BITS", "DAC_MAX", "COMMAND_BUFFER",)


def as_dict() -> dict:
    """Reported on /status so a mismatch is visible without a trace."""
    return {name: globals()[name] for name in SHARED}
