#!/usr/bin/env python3
"""Generate firmware/constants.h and injection_monitor/constants.py.

Run from test/check.sh (or a pre-commit hook) with --check to fail the build if
the generated files have drifted from shared/constants.json.

Usage:
    python3 tools/gen_constants.py            # regenerate
    python3 tools/gen_constants.py --check    # verify only, non-zero on drift
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "shared" / "constants.json"
H_OUT = ROOT / "firmware" / "constants.h"
PY_OUT = ROOT / "injection_monitor" / "constants.py"

BANNER = "GENERATED by tools/gen_constants.py from shared/constants.json."
WARNING = "Do not edit. Edit the JSON and regenerate."


def render_h(spec: dict) -> str:
    lines = [
        "// " + BANNER,
        "// " + WARNING,
        "",
        "#ifndef INJECTION_CONSTANTS_H",
        "#define INJECTION_CONSTANTS_H",
        "",
        "// ---- shared with the host ----",
    ]
    for section in ("shared", "firmware_only"):
        if section == "firmware_only":
            lines += ["", "// ---- firmware only ----"]
        for name, e in spec[section].items():
            doc = f"  // {e['doc']}" if e.get("doc") else ""
            lines.append(f"#define {name} {e['value']}{doc}")
    lines += ["", "#endif  // INJECTION_CONSTANTS_H", ""]
    return "\n".join(lines)


def render_py(spec: dict) -> str:
    lines = [
        f'"""{BANNER}',
        "",
        f"{WARNING}",
        '"""',
        "",
        "from __future__ import annotations",
        "",
    ]
    for name, e in spec["shared"].items():
        if e.get("doc"):
            lines.append(f"#: {e['doc']}")
        value = e["value"]
        lines.append(f"{name} = {value!r}" if e["type"] != "raw" else f'{name} = "{value}"')
    lines += [
        "",
        "#: Highest valid high byte of a little-endian ADC sample. A valid",
        "#: trace has every high byte at or below this; ASCII never is, which",
        "#: is how a short trace padded by the next block's text is detected.",
        "MAX_SAMPLE_HIGH_BYTE = (1 << (ADC_BITS - 8)) - 1",
        "",
        "#: Names that must agree with the firmware, for the startup check.",
        "SHARED = (" + ", ".join(f'"{n}"' for n in spec["shared"]) + ",)",
        "",
        "",
        "def as_dict() -> dict:",
        '    """Reported on /status so a mismatch is visible without a trace."""',
        "    return {name: globals()[name] for name in SHARED}",
        "",
    ]
    return "\n".join(lines)


def scan_ino(path: Path, spec: dict) -> list[str]:
    """Compare against the #define lines actually present in a firmware file.

    This is the check that catches the failure the generator exists to
    prevent: the JSON and the generated files can agree perfectly while the
    .ino has drifted away from both. A name absent from the firmware is not an
    error -- it may simply be host-side, like ADC_BITS.
    """
    text = path.read_text(errors="replace")
    problems = []
    for section in ("shared", "firmware_only"):
        for name, e in spec[section].items():
            m = re.search(rf"^\s*#define\s+{re.escape(name)}\s+(-?\d+)",
                          text, re.MULTILINE)
            if m is None:
                continue
            found = int(m.group(1))
            if found != e["value"]:
                problems.append(
                    f"{name}: {path.name} has {found}, constants.json has "
                    f"{e['value']}"
                )
    return problems


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="verify the generated files are current")
    ap.add_argument("--scan", type=Path, metavar="INO",
                    help="also compare against a firmware .ino")
    args = ap.parse_args()

    spec = json.loads(SOURCE.read_text())
    spec.pop("_comment", None)
    outputs = {H_OUT: render_h(spec), PY_OUT: render_py(spec)}

    drift = []
    for path, content in outputs.items():
        current = path.read_text() if path.exists() else None
        if current == content:
            continue
        if args.check:
            drift.append(path)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
            print(f"wrote {path.relative_to(ROOT)}")

    mismatches = scan_ino(args.scan, spec) if args.scan else []
    for m in mismatches:
        print(f"MISMATCH: {m}", file=sys.stderr)

    if drift or mismatches:
        for p in drift:
            print(f"STALE: {p.relative_to(ROOT)}", file=sys.stderr)
        print("\nRun: python3 tools/gen_constants.py, and update the firmware "
              "to match.", file=sys.stderr)
        return 1
    if args.scan:
        print(f"{args.scan.name}: all shared constants agree")
    if args.check:
        print("constants are current")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
